### ISSUE TITLE
Getting `ReferenceError: TextEncoder is not defined` when used in Node.js

### ISSUE THREAD

**Issue by lehni** [heineiuo/rippledb#148]
Buffer.js makes reference to `TExtEncoder`, but never imports it:

https://github.com/heineiuo/rippledb/blob/b88520491ef89a7025c5a67fd02845aad09a77c0/src/Buffer.ts#L95

This causes an exception on Node.js

I was using the following script to try and convert a Level DB to a Ripple DB:

```js
#!/usr/bin/env node

const fs = require('fs');
const level = require('level');
const { Database } = require('rippledb');

if(process.argv.length !== 4) {
  console.error("Usage: node level-convert.js <path_to_level_db> <path_to_ripple_db>");
  process.exit(1)
}

let levelDbPath = process.argv[2];
let rippleDbPath = process.argv[3];

try {
let stats = fs.statSync(levelDbPath);
} catch(e) {
  console.error("No such leveldb database");
  process.exit(1)  
}

if(!stats.isDirectory()) {
  console.error("No such leveldb database");
  process.exit(1)  
}

try {
  let levelDb = level(levelDbPath, {valueEncoding: 'json'});
  let rippleDb = new Database(rippleDbPath);
} catch(e) {
  console.error("Could not open leveldb database");
  process.exit(1)  
}

s = levelDb.createReadStream();

s.on('data', function({ key, value }) {
  rippleDb.put(key, value);
})
```

**Comment by lehni** [comment]
It looks like I'll have to do the same workaround as you do for tests, but shouldn't the library handle this internally?

https://github.com/heineiuo/rippledb/blob/52b8d0dd77bba75c310203b23293604461d34413/tests/filter.test.ts#L5

**Comment by heineiuo** [comment]
@lehni Thanks!  I appreciate your mentioning that.

To enable this project support both node.js and Deno(WIP), I removed all node.js modules. The line in `rippledb/tests/filter.test.ts` was added just because `jest` did not have TextEncoder in global object.

This was my mistake, and I will add global TextEncoder at `/port/node` folder if node.js version is under v11.

**Comment by lehni** [comment]
@heineiuo while we're at it: Is it a bug or a feature that I can't seem to be able to put a new value over an existing key?

**Comment by heineiuo** [comment]
@lehni It's absolutely a bug. Could you please open a new issue for that?

> @heineiuo while we're at it: Is it a bug or a feature that I can't seem to be able to put a new value over an existing key?

**Comment by lehni** [comment]
Ok, I'll investigate!

**Comment by lehni** [comment]
My bad, it was an async issue…

**Comment by heineiuo** [comment]
> My bad, it was an async issue…

haha :), nevermind, any issue will be welcomed!

**Comment by lehni** [comment]
:) BTW, why do I need to use `new TextDecoder().decode()` on the stored values even when they were stored as strings? Shouldn't I get the same thing back that I put in? And did you consider supporting a feature like `{ valueEncoding: 'json' }` on `level`?

**Comment by lehni** [comment]
(apologies for keep writing off-topic message here, but I just switched from `level` to `rippledb`, and this is just amazing: `added 1 package from 1 contributor, removed 21 packages from 12 contributors` 🎉 )

**Comment by heineiuo** [comment]
> :) BTW, why do I need to use `new TextDecoder().decode()` on the stored values even when they were stored as strings? Shouldn't I get the same thing back that I put in? And did you consider supporting a feature like `{ valueEncoding: 'json' }` on `level`?

RippleDB is more like [`leveldown`](https://github.com/Level/leveldown/) which does not have encoding option either.

RippleDB was designed to be a low level engine for data writing and reading, and use `Uint8Array` as standard data type.

In original design, It should only use `Uint8Array` type params. However, in most situation, `string` is a first choice for `key`'s encoding. So `string` was also supported in RippleDB. If user pass `string` type key or value, RippleDB will recognize it and convert it to `Uint8Array`. RippleDB doesn't store data's original encoding and cannot distinguish the right value type when reading data. so it just returns Uint8Array :(.

Here is a simple example of wrapping RippleDB to support valueEncoding:

```js
import { Database } from "rippledb";

class CustomDatabase extends Database {
  constructor(dbpath: string, options = {}, extraOptions = {}) {
    super(dbpath, options);
    this.extraOptions = extraOptions;
  }

  async customPut(key, value) {
    if (this.extraOptions.valueEncoding === "json") {
      return await this.put(key, JSON.stringify(value));
    }
    return await this.put(key, value);
  }

  async customGet(key) {
    if (this.extraOptions.valueEncoding === "json") {
      const value = await this.get(key);
      return JSON.parse(value);
    }
    if (this.extraOptions.valueEncoding === "utf8") {
      const value = await this.get(key);
      return new TextDecorder().decode(value);
    }

    return await this.get(key);
  }
}

```

**Comment by heineiuo** [comment]
> (apologies for keep writing off-topic messageshere, but I just switched from `level` to `rippledb`, and this is just amazing: `added 1 package from 1 contributor, removed 21 packages from 12 contributors` 🎉 )

I'm super glad to hear that!! 🎉  Any issues and messages are welcomed!!

**Comment by lehni** [comment]
@heineiuo this makes a lot of sense, thank you for the explanations! I think it's worth putting the above 1:1 into the README, no?

**Comment by heineiuo** [comment]
@lehni Very cool! I think i can put that in Q&A.

**Comment by selvalr** [comment]
/home/inba/Desktop/node/mongodb/node_modules/whatwg-url/lib/encoding.js:2
const utf8Encoder = new TextEncoder();
                    ^
please solve the error in node 10 version*******

ReferenceError: TextEncoder is not defined
    at Object.<anonymous> (/home/inba/Desktop/node/mongodb/node_modules/whatwg-url/lib/encoding.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/inba/Desktop/node/mongodb/node_modules/whatwg-url/lib/url-state-machine.js:5:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

**Comment by heineiuo** [comment]
> /home/inba/Desktop/node/mongodb/node_modules/whatwg-url/lib/encoding.js:2 const utf8Encoder = new TextEncoder(); ^ please solve the error in node 10 version*******
> 
> ReferenceError: TextEncoder is not defined at Object. (/home/inba/Desktop/node/mongodb/node_modules/whatwg-url/lib/encoding.js:2:21) at Module._compile (internal/modules/cjs/loader.js:778:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Module.require (internal/modules/cjs/loader.js:692:17) at require (internal/modules/cjs/helpers.js:25:18) at Object. (/home/inba/Desktop/node/mongodb/node_modules/whatwg-url/lib/url-state-machine.js:5:34) at Module._compile (internal/modules/cjs/loader.js:778:30)

@selvalr It seems like throw from `whatwg-url`, not `rippledb`

**Comment by codetycon** [comment]
This problem is caused by an incompatible version of Node.js. You must upgrade your node.js version to v14 or above.

I came across this video that goes into great detail about the problem and how to solve it: https://youtu.be/li9eZtfekl0

**Comment by Codeur16** [comment]
const utf8Encoder = new TextEncoder();
                    ^

ReferenceError: TextEncoder is not defined
I need solution for this error please?

**Comment by heineiuo** [comment]
@Codeur16 It seems like you are using node.js < 10? You can add this polyfill to your entry js file:

```js

global.TextEncoder = require('util').TextEncoder

```

However I must say upgrade your node.js to 10+ is better.
